[workspace]
members = [
    "crates/*",
    "examples/fullstack/*",
]
exclude = [
    "examples/fullstack/.stackable",
    "examples/fullstack/build",
]
resolver = "2"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = "z"
