[package]
name = "stackable-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = { version = "0.20" }
bounce = { version = "0.5", features = ["helmet"] }
