[package]
name = "stackable-backend"
version = "0.1.0"
edition = "2021"
rust-version = "1.65"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = { version = "0.20", features = ["ssr"] }
futures = { version = "0.3", default-features = false, features = ["std"] }

# Hyper Server and Tower Service.
hyper = { version = "0.14.23", features = ["runtime", "server", "http1"], optional = true }
tower-service = { version = "0.3.2", optional = true }
warp = { version = "0.3.3", default-features = false, optional = true }
tokio = { version = "1", optional = true }

[features]
tower-service = ["dep:tower-service", "dep:warp", "dep:tokio"]
hyper-server = ["dep:hyper"]
