---
name: Run Tests & Publishing

on: [push, pull_request]

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown 
          components: clippy

      - name: Restore Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-make
        uses: davidB/rust-cargo-make@v1

      - name: Run Lints
        run: ci/feature-soundness.sh

  rustfmt:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: wasm32-unknown-unknown 
          components: rustfmt

      - name: Restore Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Check Formatting
        run: cargo +nightly fmt -- --unstable-features
